{{ if and .Values.applications.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: {{ .Values.applications.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-160"
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.certManager.namespace }}
  project: {{ .Values.project.name }}
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .Values.applications.certManager.revision }}
    helm:
      valuesObject:
        {{/* todo: link logging format */}}
        {{/* todo: tracing */}}
        installCRDs: true
        extraArgs:
          - --logging-format=json
        webhook:
          extraArgs:
            - --logging-format=json
        cainjector:
          extraArgs:
            - --logging-format=json
        startupapicheck:
          podAnnotations:
            sidecar.istio.io/inject: "false"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
