{{ if and (or .Values.applications.istio.enabled (eq .Values.network.mode "istio")) .Values.applications.minio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: minio-ingress-gateway
  namespace: {{ .Values.applications.istio.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-120"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # todo: remove
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - minio.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - minio.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: minio-server-tls
{{ end }}
